n= input("Entetr name :")
a= input("Entetr age :")
g= input("Entetr gendre:")
b= input("Entetr branch :")
c= input("Entetr college name :")
print ("Name :"+n)
print ("Age :"+a)
print ("Gendre :"+g)
print ("Branch :"+b)
print ("College Name :"+college)

